from __future__ import annotations
import logging
from config.settings import get_settings

logger = logging.getLogger(__name__)


class GitHubPRCreator:
    """
    Creates GitHub Pull Requests with the generated patch using GitHub REST API.
    Uses the GitHub App installation token for authentication.
    Graceful degradation: returns None if not configured.
    """

    def __init__(self) -> None:
        self._settings = get_settings()

    async def create_pr(
        self,
        repo_full_name: str,
        fix_id: str,
        error_class: str,
        patches: list[dict],
        fix_explanation: str,
        branch_name: str | None = None,
    ) -> dict | None:
        token = await self._get_installation_token()
        if not token:
            logger.warning("GitHubPR: no install token, skipping PR creation")
            return None

        import httpx
        branch = branch_name or f"dara/fix-{error_class.lower()}-{fix_id[:8]}"
        headers = {"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json",
                   "X-GitHub-Api-Version": "2022-11-28"}
        base_url = f"https://api.github.com/repos/{repo_full_name}"

        async with httpx.AsyncClient(headers=headers, timeout=30) as client:
            # 1. Get default branch SHA
            repo_resp = await client.get(base_url)
            if repo_resp.status_code != 200:
                logger.error("GitHubPR: cannot fetch repo: %s", repo_resp.text[:200])
                return None
            default_branch = repo_resp.json().get("default_branch", "main")
            ref_resp = await client.get(f"{base_url}/git/refs/heads/{default_branch}")
            if ref_resp.status_code != 200:
                logger.error("GitHubPR: cannot fetch ref: %s", ref_resp.text[:200])
                return None
            base_sha = ref_resp.json()["object"]["sha"]

            # 2. Create feature branch
            br_resp = await client.post(f"{base_url}/git/refs",
                json={"ref": f"refs/heads/{branch}", "sha": base_sha})
            if br_resp.status_code not in (200, 201, 422):
                logger.error("GitHubPR: branch creation failed: %s", br_resp.text[:200])
                return None

            # 3. Apply patches as file updates
            for patch in patches[:3]:
                fp = patch.get("file_path","")
                fixed = patch.get("fixed_content","")
                if not fp or not fixed:
                    continue
                import base64
                file_resp = await client.get(f"{base_url}/contents/{fp}",
                                              params={"ref": branch})
                file_sha = file_resp.json().get("sha") if file_resp.status_code == 200 else None
                body = {"message": f"fix: {error_class} - DARA auto-fix",
                        "content": base64.b64encode(fixed.encode()).decode(),
                        "branch": branch}
                if file_sha:
                    body["sha"] = file_sha
                await client.put(f"{base_url}/contents/{fp}", json=body)

            # 4. Create PR
            pr_body = (
                f"## DARA Auto-Fix\n\n"
                f"**Fix ID:** `{fix_id}`\n\n"
                f"**Summary:** {fix_explanation}\n\n"
                f"---\n*Generated by DARA - Distributed Architecture Root-cause Agent*"
            )
            pr_resp = await client.post(f"{base_url}/pulls", json={
                "title": f"fix: {error_class} (DARA auto-fix)",
                "body": pr_body, "head": branch, "base": default_branch,
                "draft": True,
            })
            if pr_resp.status_code not in (200, 201):
                logger.error("GitHubPR: PR creation failed: %s", pr_resp.text[:200])
                return None

            pr_data = pr_resp.json()
            logger.info("GitHubPR: created PR #%d: %s", pr_data.get("number"), pr_data.get("html_url"))
            return {"pr_url": pr_data.get("html_url"), "pr_number": pr_data.get("number"),
                    "branch": branch}

    async def _get_installation_token(self) -> str | None:
        try:
            import time, jwt
            pem_path = self._settings.resolved_pem_path
            if not pem_path or not __import__("pathlib").Path(pem_path).exists():
                return None
            pem = __import__("pathlib").Path(pem_path).read_text()
            payload = {"iat": int(time.time()) - 60, "exp": int(time.time()) + 600,
                       "iss": self._settings.github_app_id}
            jwt_token = jwt.encode(payload, pem, algorithm="RS256")
            import httpx
            async with httpx.AsyncClient() as client:
                resp = await client.post(
                    f"https://api.github.com/app/installations/{self._settings.github_installation_id}/access_tokens",
                    headers={"Authorization": f"Bearer {jwt_token}",
                             "Accept": "application/vnd.github+json",
                             "X-GitHub-Api-Version": "2022-11-28"},
                )
                if resp.status_code == 201:
                    return resp.json().get("token")
                logger.warning("GitHubPR: token request failed %d", resp.status_code)
                return None
        except Exception as e:
            logger.warning("GitHubPR: install token error: %s", e)
            return None
