from __future__ import annotations
import logging
from config.settings import get_settings

logger = logging.getLogger(__name__)


class GitHubPRCreator:
    """
    Creates GitHub Pull Requests with the generated patch using GitHub REST API.
    Uses the GitHub App installation token for authentication.
    Graceful degradation: returns None if not configured.
    """

    def __init__(self) -> None:
        self._settings = get_settings()

    async def create_pr(
        self,
        repo_full_name: str,
        fix_id: str,
        error_class: str,
        patches: list[dict],
        fix_explanation: str,
        branch_name: str | None = None,
    ) -> dict | None:
        token = await self._get_installation_token()
        if not token:
            logger.warning("GitHubPR: no install token, skipping PR creation")
            return None

        import httpx
        branch = branch_name or f"dara/fix-{error_class.lower()}-{fix_id[:8]}"
        headers = {"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json",
                   "X-GitHub-Api-Version": "2022-11-28"}
        base_url = f"https://api.github.com/repos/{repo_full_name}"

        async with httpx.AsyncClient(headers=headers, timeout=30) as client:
            # 1. Get default branch SHA
            repo_resp = await client.get(base_url)
            if repo_resp.status_code != 200:
                logger.error("GitHubPR: cannot fetch repo: %s", repo_resp.text[:200])
                return None
            default_branch = repo_resp.json().get("default_branch", "main")
            ref_resp = await client.get(f"{base_url}/git/refs/heads/{default_branch}")
            if ref_resp.status_code != 200:
                logger.error("GitHubPR: cannot fetch ref: %s", ref_resp.text[:200])
                return None
            base_sha = ref_resp.json()["object"]["sha"]

            # 2. Create feature branch
            br_resp = await client.post(f"{base_url}/git/refs",
                json={"ref": f"refs/heads/{branch}", "sha": base_sha})
            if br_resp.status_code not in (200, 201, 422):
                logger.error("GitHubPR: branch creation failed: %s", br_resp.text[:200])
                return None

            # 3. Apply patches as file updates
            for patch in patches[:3]:
                fp = patch.get("file_path","")
                fixed = patch.get("fixed_content","")
                if not fp or not fixed:
                    continue
                import base64
                file_resp = await client.get(f"{base_url}/contents/{fp}",
                                              params={"ref": branch})
                file_sha = file_resp.json().get("sha") if file_resp.status_code == 200 else None
                body = {"message": f"fix: {error_class} - DARA auto-fix",
                        "content": base64.b64encode(fixed.encode()).decode(),
                        "branch": branch}
                if file_sha:
                    body["sha"] = file_sha
                await client.put(f"{base_url}/contents/{fp}", json=body)

            # 4. Create PR
            pr_body = (
                f"## DARA Auto-Fix\n\n"
                f"**Fix ID:** `{fix_id}`\n\n"
                f"**Summary:** {fix_explanation}\n\n"
                f"---\n*Generated by DARA - Distributed Architecture Root-cause Agent*"
            )
            pr_resp = await client.post(f"{base_url}/pulls", json={
                "title": f"fix: {error_class} (DARA auto-fix)",
                "body": pr_body, "head": branch, "base": default_branch,
                "draft": True,
            })
            if pr_resp.status_code not in (200, 201):
                logger.error("GitHubPR: PR creation failed: %s", pr_resp.text[:200])
                return None

            pr_data = pr_resp.json()
            logger.info("GitHubPR: created PR #%d: %s", pr_data.get("number"), pr_data.get("html_url"))
            return {"pr_url": pr_data.get("html_url"), "pr_number": pr_data.get("number"),
                    "branch": branch}

    async def _get_installation_token(self) -> str | None:
        try:
            import time, jwt
            pem_path = self._settings.resolved_pem_path
            if not pem_path or not __import__("pathlib").Path(pem_path).exists():
                return None
            pem = __import__("pathlib").Path(pem_path).read_text()
            payload = {"iat": int(time.time()) - 60, "exp": int(time.time()) + 600,
                       "iss": self._settings.github_app_id}
            jwt_token = jwt.encode(payload, pem, algorithm="RS256")
            import httpx
            async with httpx.AsyncClient() as client:
                resp = await client.post(
                    f"https://api.github.com/app/installations/{self._settings.github_installation_id}/access_tokens",
                    headers={"Authorization": f"Bearer {jwt_token}",
                             "Accept": "application/vnd.github+json",
                             "X-GitHub-Api-Version": "2022-11-28"},
                )
                if resp.status_code == 201:
                    return resp.json().get("token")
                logger.warning("GitHubPR: token request failed %d", resp.status_code)
                return None
        except Exception as e:
            logger.warning("GitHubPR: install token error: %s", e)
            return None

    # ── Week 12: Distributed PR creation ─────────────────────

    async def create_distributed_pr(
        self,
        fault_cascade,   # FaultCascade
        fix_per_service: dict[str, dict],  # {service_name: {repo, patches, fix_explanation}}
    ) -> list[dict]:
        """
        Creates one GitHub PR per affected service repo.
        PRs cross-reference each other in their body.

        Args:
            fault_cascade: FaultCascade with trace_id, affected_services
            fix_per_service: dict mapping service_name to fix info
                {
                  "payment-svc": {
                    "repo_full_name": "org/payment",
                    "patches": [{"file_path": "...", "fixed_content": "..."}],
                    "fix_explanation": "...",
                  }
                }

        Returns:
            List of PR result dicts (one per service with a fix).
        """
        trace_short = fault_cascade.trace_id[:8]
        total_services = len(fix_per_service)
        created_prs: list[dict] = []

        # First pass: create all PRs, collect URLs
        pr_results: dict[str, dict | None] = {}
        for idx, (service_name, fix_info) in enumerate(fix_per_service.items(), 1):
            repo = fix_info.get("repo_full_name", "")
            if not repo:
                logger.warning(
                    "create_distributed_pr: no repo for service %s, skipping", service_name
                )
                pr_results[service_name] = None
                continue

            branch = f"dara/distributed-fix-{trace_short}-{service_name[:12]}"
            explanation = fix_info.get("fix_explanation", "Distributed bug fix")

            pr = await self.create_pr(
                repo_full_name=repo,
                fix_id=f"{trace_short}-{idx}",
                error_class=f"distributed_bug (trace {trace_short})",
                patches=fix_info.get("patches", []),
                fix_explanation=explanation,
                branch_name=branch,
            )
            pr_results[service_name] = pr
            if pr:
                created_prs.append({
                    "service_name": service_name,
                    "repo": repo,
                    **pr,
                })

        # Second pass: add cross-reference comments to all created PRs
        all_pr_urls = [r["pr_url"] for r in created_prs if r.get("pr_url")]
        if len(all_pr_urls) > 1:
            token = await self._get_installation_token()
            if token:
                await self._add_crossref_comments(
                    created_prs, all_pr_urls, fault_cascade, token
                )

        logger.info(
            "create_distributed_pr: created %d/%d PRs for trace %s",
            len(created_prs), total_services, trace_short,
        )
        return created_prs

    async def _add_crossref_comments(
        self,
        created_prs: list[dict],
        all_pr_urls: list[str],
        fault_cascade,
        token: str,
    ) -> None:
        """Add a cross-reference comment to each PR listing the other fix PRs."""
        import httpx

        headers = {
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
        }

        for pr_info in created_prs:
            repo = pr_info.get("repo", "")
            pr_number = pr_info.get("pr_number")
            if not repo or not pr_number:
                continue

            other_urls = [u for u in all_pr_urls if u != pr_info.get("pr_url")]
            other_links = "\n".join(f"- {u}" for u in other_urls)

            comment_body = (
                f"## 🔗 Distributed Fix — Cross-References\n\n"
                f"This PR is **part {created_prs.index(pr_info) + 1}/"
                f"{len(created_prs)}** of a distributed bug fix.\n\n"
                f"**Trace ID:** `{fault_cascade.trace_id}`  \n"
                f"**Root service:** `{fault_cascade.root_service}`  \n"
                f"**Propagation:** {' → '.join(fault_cascade.propagation_path)}\n\n"
                f"### Other PRs in this fix\n{other_links}\n\n"
                f"*All PRs must be merged together for the full fix to take effect.*\n"
                f"*Generated by DARA Distributed Bug Fixer.*"
            )
            try:
                async with httpx.AsyncClient(headers=headers, timeout=15) as client:
                    await client.post(
                        f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments",
                        json={"body": comment_body},
                    )
            except Exception as e:
                logger.warning(
                    "create_distributed_pr: crossref comment failed for %s#%s: %s",
                    repo, pr_number, e,
                )

