"""
tests/test_rlhf_blast_radius.py
=================================
Unit tests for:
  - PRFeedbackProcessor (RLHF: merged / changes_requested / closed)
  - GitHub webhook endpoint (HMAC verification, event routing, 202 response)
  - BlastRadiusAnalyzer (risk classification, API contract detection, consumer tests)
  - Polyglot ASTChunker (Go, TypeScript, fallback)
"""
from __future__ import annotations

import hashlib
import hmac
import json
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from fastapi.testclient import TestClient

from api.models.agent_schemas import Fix, PatchFile
from context.ast_chunker import ASTChunker
from feedback.pr_feedback_processor import PRFeedbackProcessor, _extract_fix_id
from graph.blast_radius import BlastRadiusAnalyzer, BlastRadiusReport


# ──────────────────────────────────────────────────────────────────────────────
# Fixtures
# ──────────────────────────────────────────────────────────────────────────────

SAMPLE_FIX_ID = "abc12345-def6-7890-gh12-ijklmnop3456"
SAMPLE_PR_BODY = (
    "## DARA Auto-Fix\n\n"
    f"**Fix ID:** `{SAMPLE_FIX_ID}`\n\n"
    "**Summary:** Fixed null pointer in payment handler\n\n"
    "---\n*Generated by DARA*"
)


def make_patch(file_path: str = "app/main.py", diff: str = "+x = 1\n") -> PatchFile:
    return PatchFile(
        file_path=file_path, unified_diff=diff,
        lines_changed=1, change_description="test",
    )


def make_fix(patches=None) -> Fix:
    patches = patches or [make_patch()]
    return Fix(
        error_id="err-001", patches=patches,
        total_files_changed=len(patches), total_lines_changed=1,
        fix_explanation="test fix", suggested_tests=[],
        confidence_retained=0.8, regression_risk="low",
        strategy="llm_single_file", llm_provider="groq",
    )


def _make_processor(qdrant=None, neo4j=None, postgres=None, memory=None):
    return PRFeedbackProcessor(
        qdrant=qdrant or AsyncMock(),
        neo4j=neo4j or AsyncMock(),
        postgres=postgres or AsyncMock(),
        memory=memory or AsyncMock(),
    )


# ──────────────────────────────────────────────────────────────────────────────
# Feature 3: RLHF — PRFeedbackProcessor
# ──────────────────────────────────────────────────────────────────────────────

class TestPRFeedbackProcessor:

    @pytest.mark.asyncio
    async def test_pr_merged_marks_highly_reliable(self):
        """Merged PR → Qdrant outcome=highly_reliable, Neo4j acceptance++."""
        mock_qdrant = AsyncMock()
        mock_neo4j = AsyncMock()
        mock_postgres = AsyncMock()

        # Simulate DB returning fix row with error_id
        fix_row = MagicMock()
        fix_row.error_id = "error-uuid-001"
        mock_postgres.get_fix_by_id.return_value = fix_row

        err_row = MagicMock()
        err_row.error_class = "NullPointerException"
        mock_postgres.get_error.return_value = err_row

        processor = _make_processor(
            qdrant=mock_qdrant, neo4j=mock_neo4j, postgres=mock_postgres
        )
        result = await processor.on_pr_merged(SAMPLE_PR_BODY, pr_number=42)

        assert result.fix_id == SAMPLE_FIX_ID
        assert result.event_type == "merged"
        assert result.qdrant_updated is True
        assert result.neo4j_updated is True

        # Check Qdrant payload content
        qdrant_call = mock_qdrant.set_payload_fields.call_args
        assert qdrant_call[0][1]["outcome"] == "highly_reliable"
        assert qdrant_call[0][1]["reliability_score"] == 1.0
        assert qdrant_call[0][1]["human_merged"] is True

        # Check Neo4j acceptance was incremented
        mock_neo4j.increment_pattern_acceptance.assert_called_once()

    @pytest.mark.asyncio
    async def test_pr_closed_marks_negative_example(self):
        """Closed (not merged) PR → Qdrant outcome=negative_example, Neo4j rejection++."""
        mock_qdrant = AsyncMock()
        mock_neo4j = AsyncMock()
        mock_postgres = AsyncMock()

        fix_row = MagicMock()
        fix_row.error_id = "error-uuid-002"
        mock_postgres.get_fix_by_id.return_value = fix_row

        err_row = MagicMock()
        err_row.error_class = "IndexError"
        mock_postgres.get_error.return_value = err_row

        processor = _make_processor(
            qdrant=mock_qdrant, neo4j=mock_neo4j, postgres=mock_postgres
        )
        result = await processor.on_pr_closed(SAMPLE_PR_BODY, pr_number=43)

        assert result.event_type == "closed"
        assert result.qdrant_updated is True
        assert result.neo4j_updated is True

        qdrant_call = mock_qdrant.set_payload_fields.call_args
        assert qdrant_call[0][1]["outcome"] == "negative_example"
        assert qdrant_call[0][1]["reliability_score"] == -1.0
        assert qdrant_call[0][1]["human_rejected"] is True

        mock_neo4j.increment_pattern_rejection.assert_called_once()

    @pytest.mark.asyncio
    async def test_pr_changes_requested_stores_feedback(self):
        """Changes-requested → Qdrant stores human_feedback, PatternMemory records failure."""
        mock_qdrant = AsyncMock()
        mock_memory = AsyncMock()
        mock_postgres = AsyncMock()

        fix_row = MagicMock()
        fix_row.error_id = "error-uuid-003"
        mock_postgres.get_fix_by_id.return_value = fix_row

        err_row = MagicMock()
        err_row.error_class = "TypeError"
        mock_postgres.get_error.return_value = err_row

        processor = _make_processor(
            qdrant=mock_qdrant, postgres=mock_postgres, memory=mock_memory
        )
        review_comment = "The null check is missing in the handler. Please add it."
        result = await processor.on_changes_requested(
            SAMPLE_PR_BODY, review_comment, pr_number=44
        )

        assert result.event_type == "changes_requested"
        assert result.qdrant_updated is True
        assert result.memory_updated is True

        qdrant_call = mock_qdrant.set_payload_fields.call_args
        assert "human_feedback" in qdrant_call[0][1]
        assert review_comment[:50] in qdrant_call[0][1]["human_feedback"]
        assert qdrant_call[0][1]["outcome"] == "needs_revision"

        mock_memory.record_failure.assert_called_once()
        call_kwargs = mock_memory.record_failure.call_args[1]
        assert review_comment[:50] in call_kwargs.get("failure_reason", "")

    @pytest.mark.asyncio
    async def test_non_dara_pr_is_silently_skipped(self):
        """Non-DARA PR body (no Fix ID) → processor skips all updates."""
        mock_qdrant = AsyncMock()
        mock_neo4j = AsyncMock()

        processor = _make_processor(qdrant=mock_qdrant, neo4j=mock_neo4j)
        result = await processor.on_pr_merged("## Some other PR\n\nNo DARA content", pr_number=99)

        assert result.fix_id == ""
        assert result.qdrant_updated is False
        assert result.neo4j_updated is False
        mock_qdrant.set_payload_fields.assert_not_called()

    def test_extract_fix_id_from_pr_body(self):
        assert _extract_fix_id(SAMPLE_PR_BODY) == SAMPLE_FIX_ID

    def test_extract_fix_id_returns_none_for_non_dara(self):
        assert _extract_fix_id("Some random PR body") is None

    def test_extract_fix_id_returns_none_for_empty(self):
        assert _extract_fix_id("") is None


# ──────────────────────────────────────────────────────────────────────────────
# Feature 3: Webhook HMAC verification
# ──────────────────────────────────────────────────────────────────────────────

class TestGitHubWebhookEndpoint:

    def _make_client(self):
        from fastapi import FastAPI
        from api.routes.webhook_github import router
        app = FastAPI()
        app.include_router(router)
        return TestClient(app, raise_server_exceptions=False)

    def _sign_body(self, body: bytes, secret: str) -> str:
        return "sha256=" + hmac.new(secret.encode(), body, hashlib.sha256).hexdigest()

    def test_invalid_signature_returns_403(self):
        client = self._make_client()
        body = json.dumps({"action": "closed"}).encode()
        with patch("api.routes.webhook_github.get_settings") as mock_settings:
            mock_settings.return_value.github_webhook_secret = "real-secret"
            response = client.post(
                "/webhooks/github/pr-feedback",
                content=body,
                headers={
                    "X-GitHub-Event": "pull_request",
                    "X-Hub-Signature-256": "sha256=bad_signature",
                    "Content-Type": "application/json",
                },
            )
        assert response.status_code == 403

    def test_valid_signature_returns_202(self):
        client = self._make_client()
        payload = {
            "action": "closed",
            "pull_request": {
                "number": 1,
                "body": SAMPLE_PR_BODY,
                "merged": True,
            },
        }
        body = json.dumps(payload).encode()
        secret = "test-webhook-secret"
        sig = self._sign_body(body, secret)

        mock_processor = MagicMock()
        mock_processor.on_pr_merged = AsyncMock(return_value=MagicMock())

        with (
            patch("api.routes.webhook_github.get_settings") as mock_settings,
            patch("api.routes.webhook_github._get_processor", return_value=mock_processor),
        ):
            mock_settings.return_value.github_webhook_secret = secret
            response = client.post(
                "/webhooks/github/pr-feedback",
                content=body,
                headers={
                    "X-GitHub-Event": "pull_request",
                    "X-Hub-Signature-256": sig,
                    "Content-Type": "application/json",
                },
            )
        # FastAPI TestClient may return 200 or 202 depending on how BackgroundTasks run
        assert response.status_code in (200, 202)
        assert response.json()["status"] == "accepted"

    def test_ping_event_returns_200_pong(self):
        client = self._make_client()
        body = json.dumps({"zen": "Keep it logically awesome."}).encode()
        with patch("api.routes.webhook_github.get_settings") as mock_settings:
            mock_settings.return_value.github_webhook_secret = ""
            response = client.post(
                "/webhooks/github/pr-feedback",
                content=body,
                headers={
                    "X-GitHub-Event": "ping",
                    "Content-Type": "application/json",
                },
            )
        assert response.status_code == 200
        assert response.json()["status"] == "pong"


# ──────────────────────────────────────────────────────────────────────────────
# Feature 4: Blast Radius Analyzer
# ──────────────────────────────────────────────────────────────────────────────

class TestBlastRadiusAnalyzer:

    @pytest.mark.asyncio
    async def test_low_risk_single_downstream(self):
        """1 downstream service, no API contract → risk=low."""
        mock_neo4j = AsyncMock()
        mock_neo4j.get_downstream_services.return_value = [
            {"service": "billing-svc", "hop_count": 1, "call_count": 100}
        ]
        mock_neo4j.get_callers.return_value = []

        analyzer = BlastRadiusAnalyzer(neo4j=mock_neo4j)
        fix = make_fix([make_patch("app/utils.py", "+def helper(): pass\n")])
        report = await analyzer.analyze(fix, "payment-svc")

        assert report.risk_level == "low"
        assert report.downstream_count == 1
        assert not report.has_contract_change

    @pytest.mark.asyncio
    async def test_medium_risk_multiple_downstream(self):
        """2 downstream services, no API contract → risk=medium."""
        mock_neo4j = AsyncMock()
        mock_neo4j.get_downstream_services.return_value = [
            {"service": "billing-svc", "hop_count": 1, "call_count": 100},
            {"service": "audit-svc", "hop_count": 2, "call_count": 50},
        ]
        mock_neo4j.get_callers.return_value = []

        analyzer = BlastRadiusAnalyzer(neo4j=mock_neo4j)
        fix = make_fix()
        report = await analyzer.analyze(fix, "payment-svc")

        assert report.risk_level == "medium"

    @pytest.mark.asyncio
    async def test_high_risk_api_contract_modified(self):
        """API contract file modified → risk=high."""
        mock_neo4j = AsyncMock()
        mock_neo4j.get_downstream_services.return_value = [
            {"service": "billing-svc", "hop_count": 1, "call_count": 100}
        ]
        mock_neo4j.get_callers.return_value = []

        # Diff that adds a FastAPI route
        route_diff = '+@router.get("/payments/{id}")\n+async def get_payment(id: str): ...\n'
        fix = make_fix([make_patch("api/routes/payments.py", route_diff)])

        analyzer = BlastRadiusAnalyzer(neo4j=mock_neo4j)
        report = await analyzer.analyze(fix, "payment-svc")

        assert report.has_contract_change
        assert report.risk_level in ("high", "critical")

    @pytest.mark.asyncio
    async def test_critical_risk_api_contract_many_downstream(self):
        """API contract + >3 downstream → risk=critical."""
        mock_neo4j = AsyncMock()
        mock_neo4j.get_downstream_services.return_value = [
            {"service": f"svc-{i}", "hop_count": 1, "call_count": 10}
            for i in range(4)   # 4 downstream services
        ]
        mock_neo4j.get_callers.return_value = []

        route_diff = '+@app.post("/orders")\n+async def create_order(): ...\n'
        fix = make_fix([make_patch("api/routes/orders.py", route_diff)])

        analyzer = BlastRadiusAnalyzer(neo4j=mock_neo4j)
        report = await analyzer.analyze(fix, "order-svc")

        assert report.risk_level == "critical"
        assert report.downstream_count == 4

    @pytest.mark.asyncio
    async def test_api_contract_detected_by_path(self):
        """File in routes/ directory is auto-detected as API contract."""
        mock_neo4j = AsyncMock()
        mock_neo4j.get_downstream_services.return_value = []
        mock_neo4j.get_callers.return_value = []

        fix = make_fix([make_patch("api/routes/orders.py", "+x = 1\n")])
        analyzer = BlastRadiusAnalyzer(neo4j=mock_neo4j)
        report = await analyzer.analyze(fix, "order-svc")

        assert "api/routes/orders.py" in report.shared_api_contracts

    @pytest.mark.asyncio
    async def test_consumer_tests_triggered_when_contract_modified(self):
        """When API contract modified + downstream services exist, TestRunner is called."""
        mock_neo4j = AsyncMock()
        mock_neo4j.get_downstream_services.return_value = [
            {"service": "billing-svc", "hop_count": 1, "call_count": 100}
        ]
        mock_neo4j.get_callers.return_value = []

        route_diff = '+@router.post("/charge")\n+async def charge(): ...\n'
        fix = make_fix([make_patch("api/routes/charge.py", route_diff)])

        from validation.test_runner import TestRunResult
        mock_tr = TestRunResult(
            passed=True, test_count=5, tests_passed=5,
            tests_failed=0, coverage_pct=None, duration_ms=200,
        )

        analyzer = BlastRadiusAnalyzer(neo4j=mock_neo4j, repo_path=".")
        with patch("validation.test_runner.TestRunner") as MockRunner:
            MockRunner.return_value.run = AsyncMock(return_value=mock_tr)
            report = await analyzer.analyze(fix, "payment-svc")

        # Consumer test triggered for billing-svc
        assert len(report.consumer_test_results) > 0

    @pytest.mark.asyncio
    async def test_neo4j_unavailable_returns_low_risk(self):
        """If Neo4j is None, analysis returns low risk rather than crashing."""
        analyzer = BlastRadiusAnalyzer(neo4j=None)
        fix = make_fix()
        report = await analyzer.analyze(fix, "some-svc")

        assert report.risk_level == "low"
        assert report.downstream_count == 0


# ──────────────────────────────────────────────────────────────────────────────
# Feature 4b: Polyglot AST Chunker
# ──────────────────────────────────────────────────────────────────────────────

class TestPolyglotASTChunker:

    def test_python_file_produces_function_chunks(self):
        chunker = ASTChunker()
        source = """\
def greet(name: str) -> str:
    msg = f"Hello, {name}!"
    return msg

class UserHandler:
    def handle(self, request):
        result = self.process(request)
        return result

    def process(self, request):
        validated = self._validate(request)
        return validated
"""
        chunks = chunker.chunk_file("app.py", source=source)
        fn_names = [c.function_name for c in chunks if c.function_name]
        assert "greet" in fn_names

    def test_go_file_fallback_on_missing_lib(self):
        """Go chunker gracefully falls back to line-window when tree-sitter-go missing."""
        chunker = ASTChunker()
        # Force go parser to None
        chunker._parsers["go"] = None

        source = """\
package main

import "fmt"

func Greet(name string) string {
    return fmt.Sprintf("Hello, %s!", name)
}

func main() {
    fmt.Println(Greet("world"))
}
"""
        chunks = chunker.chunk_file("main.go", source=source)
        # Fallback produces at least one chunk
        assert len(chunks) >= 1
        assert all(c.language == "go" for c in chunks)

    def test_typescript_file_fallback_on_missing_lib(self):
        """TS chunker gracefully falls back when tree-sitter-typescript missing."""
        chunker = ASTChunker()
        chunker._parsers["typescript"] = None

        source = """\
export async function fetchUser(id: string): Promise<User> {
    const response = await fetch(`/api/users/${id}`);
    return response.json();
}

const processOrder = async (order: Order) => {
    return await db.save(order);
};
"""
        chunks = chunker.chunk_file("user.ts", source=source)
        assert len(chunks) >= 1
        assert all(c.language == "typescript" for c in chunks)

    def test_go_ast_chunks_functions_when_parser_available(self):
        """If tree-sitter-go is installed, produce function-level Go chunks."""
        chunker = ASTChunker()
        if chunker._parsers.get("go") is None:
            pytest.skip("tree-sitter-go not installed")

        source = """\
package payments

import "errors"

func Charge(amount float64) error {
    if amount <= 0 {
        return errors.New("invalid amount")
    }
    return nil
}

func Refund(txID string) error {
    return nil
}
"""
        chunks = chunker.chunk_file("payments.go", source=source)
        fn_names = [c.function_name for c in chunks if c.function_name]
        assert "Charge" in fn_names or len(chunks) >= 1  # fallback also acceptable

    def test_typescript_ast_chunks_functions_when_parser_available(self):
        """If tree-sitter-typescript is installed, produce function-level TS chunks."""
        chunker = ASTChunker()
        if chunker._parsers.get("typescript") is None:
            pytest.skip("tree-sitter-typescript not installed")

        source = """\
export async function createOrder(data: OrderData): Promise<Order> {
    const order = new Order(data);
    await order.save();
    return order;
}

export class OrderService {
    async cancel(id: string): Promise<void> {
        await Order.delete(id);
    }
}
"""
        chunks = chunker.chunk_file("orders.ts", source=source)
        fn_names = [c.function_name for c in chunks if c.function_name]
        assert "createOrder" in fn_names or len(chunks) >= 1

    def test_unknown_language_uses_fallback(self):
        """File with unknown extension uses sliding-window fallback."""
        chunker = ASTChunker()
        source = "\n".join(f"line {i}" for i in range(100))
        chunks = chunker.chunk_file("script.rb", source=source)
        assert len(chunks) >= 1
        assert all(c.language == "ruby" for c in chunks)
