"""
DARA — Prometheus Metrics Registry
====================================
All application metrics defined in one place. Import this module anywhere
to emit metrics — prometheus_client handles the global registry automatically.

Metrics catalogue:
  Counters:
    dara_errors_ingested_total          — errors received, labelled by service + severity
    dara_pipelines_total                — pipeline runs, labelled by status (fixed/failed/escalated)
    dara_fixes_generated_total          — fixes produced, labelled by strategy
    dara_fixes_reviewed_total           — reviewer decisions, labelled by recommendation
    dara_hitl_decisions_total           — Slack/API approve/reject events
    dara_duplicates_detected_total      — dedup hits by service
    dara_llm_requests_total             — LLM calls, labelled by provider + status
    dara_patch_apply_total              — patch application results, labelled by outcome

  Histograms:
    dara_pipeline_duration_seconds      — full pipeline latency
    dara_llm_latency_seconds            — per LLM call latency, labelled by provider
    dara_patch_apply_duration_seconds   — patch apply + validate time

  Gauges:
    dara_active_pipelines               — currently running pipelines
    dara_pattern_library_size           — total active patterns in pattern_library
"""
from __future__ import annotations

from prometheus_client import Counter, Gauge, Histogram

# ── Counters ──────────────────────────────────────────────────

errors_ingested = Counter(
    "dara_errors_ingested_total",
    "Total errors ingested",
    ["service", "severity"],
)

pipelines_total = Counter(
    "dara_pipelines_total",
    "Pipeline runs by final status",
    ["status"],  # fixed | failed | escalated | skipped
)

fixes_generated = Counter(
    "dara_fixes_generated_total",
    "Fixes generated by the FixerAgent",
    ["strategy"],  # llm_single_file | llm_multi_file | template_based
)

fixes_reviewed = Counter(
    "dara_fixes_reviewed_total",
    "Reviewer decisions",
    ["recommendation"],  # approve | approve_with_comments | reject
)

hitl_decisions = Counter(
    "dara_hitl_decisions_total",
    "Human-in-the-loop decisions via Slack or REST API",
    ["action", "channel"],  # action=approve|reject  channel=slack|api
)

duplicates_detected = Counter(
    "dara_duplicates_detected_total",
    "Duplicate errors blocked by deduplicator",
    ["service"],
)

llm_requests = Counter(
    "dara_llm_requests_total",
    "LLM API calls",
    ["provider", "status"],  # provider=groq|gemini|ollama  status=success|error|cached
)

patch_apply_total = Counter(
    "dara_patch_apply_total",
    "Patch application attempts",
    ["outcome"],  # success | validation_failed | apply_failed
)

# ── Histograms ────────────────────────────────────────────────

pipeline_duration = Histogram(
    "dara_pipeline_duration_seconds",
    "Full pipeline execution time in seconds",
    buckets=[1, 5, 10, 30, 60, 120, 300],
)

llm_latency = Histogram(
    "dara_llm_latency_seconds",
    "LLM API call latency",
    ["provider"],
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0],
)

patch_apply_duration = Histogram(
    "dara_patch_apply_duration_seconds",
    "Patch application + validation time",
    buckets=[0.1, 0.5, 1.0, 5.0, 10.0],
)

# ── Gauges ────────────────────────────────────────────────────

active_pipelines = Gauge(
    "dara_active_pipelines",
    "Number of pipelines currently being processed",
)

pattern_library_size = Gauge(
    "dara_pattern_library_size",
    "Number of active patterns in the pattern library",
)

# -- Rate Limiting (Week 10-11) -------
from prometheus_client import Counter as _Counter

rate_limit_hits = _Counter(
    'dara_rate_limit_hits_total',
    'Number of requests rejected by rate limiter',
    ['key_type'],
)

# -- Phase 3: Reflexive Memory Metrics (Week 15-20) ----------
strategy_failures = Counter(
    'dara_strategy_failures_total',
    'Error class fixed by a strategy that keeps failing',
    ['error_class', 'strategy'],
)

ab_test_promotions = Counter(
    'dara_ab_test_promotions_total',
    'Number of A/B test winners promoted to active',
    ['error_class'],
)

memory_graph_nodes = Gauge(
    'dara_memory_graph_nodes',
    'Count of nodes in the Neo4j institutional memory graph',
    ['node_type'],
)

anomaly_score = Gauge(
    'dara_anomaly_score',
    'Current Z-score anomaly level per service and metric',
    ['service', 'metric'],
)

anomalies_detected = Counter(
    'dara_anomalies_detected_total',
    'Proactive anomalies detected by AnomalyDetector',
    ['service', 'alert_type'],
)

fine_tuning_triples = Counter(
    'dara_fine_tuning_triples_total',
    'Training triples exported to MinIO',
)

# ── LLM Cost Tracking (Item 15) ───────────────────────────────────────────────
#
# Track token usage and estimated USD cost per LLM provider.
# Emit these metrics by calling:
#
#   from monitoring import metrics
#   metrics.llm_tokens_total.labels(provider="groq", token_type="prompt").inc(prompt_tokens)
#   metrics.llm_tokens_total.labels(provider="groq", token_type="completion").inc(completion_tokens)
#   metrics.llm_cost_usd_total.labels(provider="groq").inc(estimated_usd)
#
# Pricing reference (update when provider prices change):
#   Groq:        $0.05 / 1M input tokens,  $0.08 / 1M output tokens
#   Gemini Flash: $0.075 / 1M input,       $0.30  / 1M output
#   Gemini Pro:   $3.50  / 1M input,       $10.50 / 1M output
#   Ollama:       $0.00  (local)
#
# Grafana dashboard query:
#   sum(rate(dara_llm_estimated_cost_usd_total[24h])) by (provider)
#   sum(dara_llm_tokens_total) by (provider, token_type)

llm_tokens_total = Counter(
    "dara_llm_tokens_total",
    "Total LLM tokens processed, labelled by provider and token type (prompt/completion)",
    ["provider", "token_type"],   # token_type: prompt | completion
)

llm_cost_usd_total = Counter(
    "dara_llm_estimated_cost_usd_total",
    "Estimated total LLM cost in USD based on provider pricing at time of request",
    ["provider"],
)

llm_token_batch_size = Histogram(
    "dara_llm_token_batch_size",
    "Distribution of LLM request sizes in tokens (prompt + completion)",
    ["provider"],
    buckets=[128, 256, 512, 1024, 2048, 4096, 8192, 16384],
)

# ── Per-provider USD pricing constants (per 1M tokens) ───────────────────────
# Used by llm_router.py to compute estimated cost before emitting metrics.
LLM_PRICING_USD_PER_1M = {
    # (input_price, output_price)
    "groq":          (0.05,  0.08),
    "gemini_flash":  (0.075, 0.30),
    "gemini_pro":    (3.50, 10.50),
    "ollama":        (0.00,  0.00),   # local, no cost
}


def estimate_llm_cost_usd(
    provider: str,
    prompt_tokens: int,
    completion_tokens: int,
) -> float:
    """
    Compute estimated USD cost for an LLM call.
    Uses LLM_PRICING_USD_PER_1M pricing table.
    Returns 0.0 if provider is unknown.
    """
    input_price, output_price = LLM_PRICING_USD_PER_1M.get(provider, (0.0, 0.0))
    return (
        prompt_tokens / 1_000_000 * input_price
        + completion_tokens / 1_000_000 * output_price
    )

