"""
DARA — Prometheus Metrics Registry
====================================
All application metrics defined in one place. Import this module anywhere
to emit metrics — prometheus_client handles the global registry automatically.

Metrics catalogue:
  Counters:
    dara_errors_ingested_total          — errors received, labelled by service + severity
    dara_pipelines_total                — pipeline runs, labelled by status (fixed/failed/escalated)
    dara_fixes_generated_total          — fixes produced, labelled by strategy
    dara_fixes_reviewed_total           — reviewer decisions, labelled by recommendation
    dara_hitl_decisions_total           — Slack/API approve/reject events
    dara_duplicates_detected_total      — dedup hits by service
    dara_llm_requests_total             — LLM calls, labelled by provider + status
    dara_patch_apply_total              — patch application results, labelled by outcome

  Histograms:
    dara_pipeline_duration_seconds      — full pipeline latency
    dara_llm_latency_seconds            — per LLM call latency, labelled by provider
    dara_patch_apply_duration_seconds   — patch apply + validate time

  Gauges:
    dara_active_pipelines               — currently running pipelines
    dara_pattern_library_size           — total active patterns in pattern_library
"""
from __future__ import annotations

from prometheus_client import Counter, Gauge, Histogram

# ── Counters ──────────────────────────────────────────────────

errors_ingested = Counter(
    "dara_errors_ingested_total",
    "Total errors ingested",
    ["service", "severity"],
)

pipelines_total = Counter(
    "dara_pipelines_total",
    "Pipeline runs by final status",
    ["status"],  # fixed | failed | escalated | skipped
)

fixes_generated = Counter(
    "dara_fixes_generated_total",
    "Fixes generated by the FixerAgent",
    ["strategy"],  # llm_single_file | llm_multi_file | template_based
)

fixes_reviewed = Counter(
    "dara_fixes_reviewed_total",
    "Reviewer decisions",
    ["recommendation"],  # approve | approve_with_comments | reject
)

hitl_decisions = Counter(
    "dara_hitl_decisions_total",
    "Human-in-the-loop decisions via Slack or REST API",
    ["action", "channel"],  # action=approve|reject  channel=slack|api
)

duplicates_detected = Counter(
    "dara_duplicates_detected_total",
    "Duplicate errors blocked by deduplicator",
    ["service"],
)

llm_requests = Counter(
    "dara_llm_requests_total",
    "LLM API calls",
    ["provider", "status"],  # provider=groq|gemini|ollama  status=success|error|cached
)

patch_apply_total = Counter(
    "dara_patch_apply_total",
    "Patch application attempts",
    ["outcome"],  # success | validation_failed | apply_failed
)

# ── Histograms ────────────────────────────────────────────────

pipeline_duration = Histogram(
    "dara_pipeline_duration_seconds",
    "Full pipeline execution time in seconds",
    buckets=[1, 5, 10, 30, 60, 120, 300],
)

llm_latency = Histogram(
    "dara_llm_latency_seconds",
    "LLM API call latency",
    ["provider"],
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0],
)

patch_apply_duration = Histogram(
    "dara_patch_apply_duration_seconds",
    "Patch application + validation time",
    buckets=[0.1, 0.5, 1.0, 5.0, 10.0],
)

# ── Gauges ────────────────────────────────────────────────────

active_pipelines = Gauge(
    "dara_active_pipelines",
    "Number of pipelines currently being processed",
)

pattern_library_size = Gauge(
    "dara_pattern_library_size",
    "Number of active patterns in the pattern library",
)
