from __future__ import annotations
import difflib, json, logging, re
from pathlib import Path
from api.models.agent_schemas import Fix, PatchFile, RootCauseResult
from context.builder import ContextBundle

logger = logging.getLogger(__name__)
PROMPT_PATH = Path("prompts/fix_generator_v1.txt")


class FixerAgent:
    """
    Generates unified-diff patches for files listed in root_cause.files_to_change.
    Temp=0.15. Diffs generated by difflib from original vs LLM-fixed code.
    """

    def __init__(self, llm_router) -> None:
        self._llm = llm_router
        self._prompt_template = PROMPT_PATH.read_text(encoding="utf-8")

    async def generate(self, root_cause: RootCauseResult, bundle: ContextBundle, error: dict) -> Fix:
        patches: list[PatchFile] = []
        for fp in root_cause.files_to_change[:3]:
            patch = await self._fix_file(fp, root_cause, bundle, error)
            if patch:
                patches.append(patch)
        if not patches:
            logger.warning("FixerAgent: no patches generated")
            return self._empty_fix(error, root_cause)
        avg_conf = sum(root_cause.confidence for _ in patches) / len(patches)
        return Fix(
            error_id=error.get("id",""),
            patches=patches,
            total_files_changed=len(patches),
            total_lines_changed=sum(p.lines_changed for p in patches),
            fix_explanation=f"Fixed {len(patches)} file(s): {root_cause.root_cause[:200]}",
            suggested_tests=[],
            confidence_retained=round(avg_conf, 3),
            regression_risk=self._risk(patches, root_cause),
            strategy=root_cause.suggested_strategy,
            llm_provider="groq",
        )

    async def _fix_file(self, file_path: str, root_cause: RootCauseResult,
                         bundle: ContextBundle, error: dict) -> PatchFile | None:
        original = ""
        fp = Path(file_path)
        if fp.exists():
            original = fp.read_text(encoding="utf-8", errors="replace")
        elif bundle.erroring_code:
            original = bundle.erroring_code
        else:
            logger.warning("FixerAgent: file not found: %s", file_path)
            return None
        prompt = (self._prompt_template
            .replace("{{immediate_cause}}", root_cause.immediate_cause)
            .replace("{{root_cause}}", root_cause.root_cause)
            .replace("{{suggested_strategy}}", root_cause.suggested_strategy)
            .replace("{{confidence}}", str(round(root_cause.confidence, 2)))
            .replace("{{error_class}}", error.get("error_class",""))
            .replace("{{message}}", error.get("message","")[:300])
            .replace("{{file_path}}", file_path)
            .replace("{{file_content}}", original[:6000])
            .replace("{{erroring_function}}", bundle.erroring_function or "unknown")
            .replace("{{line_number}}", str(error.get("line_number","?"))))
        raw = await self._llm.complete(
            prompt=prompt,
            system="You are a code fixer. Output the complete fixed file then a JSON object.",
            temperature=0.15, max_tokens=4096, priority="high",
        )
        return self._parse(raw, file_path, original, root_cause)

    def _parse(self, raw: str, file_path: str, original: str, root_cause: RootCauseResult) -> PatchFile | None:
        data = self._extract_json(raw)
        fixed = data.get("fixed_code","")
        if not fixed:
            m = re.search(r"```(?:python)?\n(.*?)```", raw, re.DOTALL)
            fixed = m.group(1) if m else ""
        if not fixed:
            logger.warning("FixerAgent: no fixed_code for %s", file_path)
            return None
        orig_lines = original.splitlines(keepends=True)
        fixed_lines = fixed.splitlines(keepends=True)
        diff = list(difflib.unified_diff(orig_lines, fixed_lines,
                                          fromfile=f"a/{file_path}", tofile=f"b/{file_path}", lineterm=""))
        if not diff:
            logger.info("FixerAgent: no diff for %s (already correct?)", file_path)
            return None
        changed = sum(1 for l in diff if l.startswith(("+","-")) and not l.startswith(("+++","---")))
        return PatchFile(
            file_path=file_path,
            unified_diff="\n".join(diff),
            lines_changed=changed,
            change_description=data.get("fix_explanation", root_cause.root_cause[:200]),
        )

    def _extract_json(self, text: str) -> dict:
        text = re.sub(r"```(?:json)?","",text).strip()
        for pat in [r'\{"fixed_code".*\}', r"\{.*\}"]:
            m = re.search(pat, text, re.DOTALL)
            if m:
                try:
                    return json.loads(m.group())
                except json.JSONDecodeError:
                    pass
        return {}

    def _risk(self, patches: list, rc: RootCauseResult) -> str:
        total = sum(p.lines_changed for p in patches)
        if len(patches) > 2 or total > 50:
            return "high"
        if len(patches) > 1 or total > 20 or rc.confidence < 0.6:
            return "medium"
        return "low"

    def _empty_fix(self, error: dict, rc: RootCauseResult) -> Fix:
        return Fix(error_id=error.get("id",""), patches=[], total_files_changed=0,
                   total_lines_changed=0, fix_explanation="No fix generated",
                   suggested_tests=[], confidence_retained=0.0,
                   regression_risk="high", strategy=rc.suggested_strategy, llm_provider="none")
